services:
  rt-toolbox_develop:
    build:
      context: .
      dockerfile: Dockerfile.develop
    container_name: rt-toolbox_develop
    # For deploying the RT-Toolbox in a dedicated machine
    # ports:
    #   - "5672:5672"
    #
    volumes:
      - .:/workspaces/rt-toolbox
      - /Users/clpombo/sandbox/rt-constellation-experiments/rabbitmq-infrastructure/rabbitmq-infrastructure:/workspaces/rabbitmq-infrastructure     # If the RabbitMQ configuration file path is not set, it will be mounted with the current directory (.) as default value
      - /Users/clpombo/sandbox/rt-constellation-experiments/rt-monitor-rust-example-app:/workspaces/experiment     # If the experiment path is not set, it will be mounted with the current directory (.) as default value
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    # For deploying the RT-Toolbox in a Docker virtual network in the same machine of the RabbitMQ servers
    networks:
      - rabbitmq-network
    #
    command: ["sleep", "infinity"]  # Keep container alive
    stdin_open: true  # Keep STDIN open
    tty: true         # Allocate a pseudo-TTY

# For deploying the RT-Toolbox infrastructure in a Docker virtual network in the same machine of the RabbitMQ servers
networks:
  rabbitmq-network:
    external: true
#
